name: Build and Test

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        version: 12
    - name: Install
      run: yarn install
    - name: Build
      run: yarn --silent build
    - name: Test
      run: yarn --silent test
